// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var $ul, addKlass, klasses, removeKlass;
    klasses = ['focus', 'focusBefore', 'focusAfter'];
    $ul = $('ul');
    $ul.each(function() {
      var h;
      h = 0;
      $(this).children('li').each(function() {
        var _h;
        _h = $(this).height();
        if (_h > h) {
          return h = _h;
        }
      });
      return $(this).children('li').height(h);
    });
    addKlass = function(_root, _kid) {
      var $code, _id, _k;
      $code = $(_root).parent('.code');
      _id = $code.attr('id');
      _k = '.' + _id;
      $('.font ' + _k).addClass(klasses[_kid]);
      return $(_root).addClass(klasses[0]);
    };
    removeKlass = function(_root, _kid) {
      $('.font > div > div').removeClass(klasses[_kid]);
      return $(_root).removeClass(klasses[0]);
    };
    $('.code .main').hover(function() {
      return addKlass(this, 0);
    }, function() {
      return removeKlass(this, 0);
    });
    $('.code .before').hover(function() {
      return addKlass(this, 1);
    }, function() {
      return removeKlass(this, 1);
    });
    return $('.code .after').hover(function() {
      return addKlass(this, 2);
    }, function() {
      return removeKlass(this, 2);
    });
  });

}).call(this);
